name: Katalon Tests - Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: windows-latest

    steps:
    # 1️⃣ Checkout your repository
    - name: Checkout code
      uses: actions/checkout@v3

    # 2️⃣ Set up Java
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    # 3️⃣ Download Katalon Studio
    - name: Download Katalon Studio
      run: |
        Invoke-WebRequest -Uri https://github.com/katalon-studio/katalon-studio/releases/download/v10.3.1/Katalon_Studio_Windows_64-10.3.1.exe -OutFile katalon.exe

    # 4️⃣ Install Katalon (silent install)
    - name: Install Katalon Studio
      run: |
        Start-Process .\katalon.exe -ArgumentList '/S' -Wait

    # 5️⃣ Run Katalon Test Suite
    - name: Run Katalon Test Suite
      run: |
        & "C:\Program Files\Katalon\Katalon_Studio_Windows_64-10.3.1\katalon.exe" ^
          -noSplash ^
          -runMode=console ^
          -projectPath="${{ github.workspace }}\katalon-project\katalon-project.prj" ^
          -retry=0 ^
          -testSuitePath="Test Suites\TestSuite1" ^
          -executionProfile="default" ^
          -browserType="Chrome"

    # 6️⃣ Upload Katalon Reports
    - name: Upload Reports
      uses: actions/upload-artifact@v3
      with:
        name: katalon-reports
        path: katalon-project\Reports\**
